// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetRts.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetRts.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231214527_AddProductionQueueAndUpgrades")]
    partial class AddProductionQueueAndUpgrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetRts.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructionProgress")
                        .HasColumnType("integer");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VisionRange")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId", "OwnerId")
                        .HasDatabaseName("IX_Buildings_Match_Owner");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Command", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BuildingType")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProcessedAtTick")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubmittedAtTick")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetBuildingId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetEntityId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetResourceDepositId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUnitIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .HasColumnType("text");

                    b.Property<string>("UpgradeType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "PlayerId", "Status")
                        .HasDatabaseName("IX_Commands_Match_Player_Status");

                    b.ToTable("Commands", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.LobbyPlayer", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatchLobbyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("LobbyId", "PlayerId");

                    b.HasIndex("MatchLobbyId");

                    b.ToTable("LobbyPlayers", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.MapTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OccupiedByBuildingId")
                        .HasColumnType("integer");

                    b.Property<int?>("OccupiedByUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("TerrainType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VisibleToPlayer1")
                        .HasColumnType("boolean");

                    b.Property<bool>("VisibleToPlayer2")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_MapTiles_Match");

                    b.ToTable("MapTiles", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommandQueueSizeLimit")
                        .HasColumnType("integer");

                    b.Property<int>("CommandsPerTick")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("GameStateSnapshot")
                        .HasColumnType("bytea");

                    b.Property<int>("MapHeight")
                        .HasColumnType("integer");

                    b.Property<int>("MapWidth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTicksPerMatch")
                        .HasColumnType("integer");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player1Resources")
                        .HasColumnType("integer");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Player2Resources")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TickIntervalMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt")
                        .HasDatabaseName("IX_Matches_EndedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Matches_Status");

                    b.HasIndex("Player1Id", "Player2Id")
                        .HasDatabaseName("IX_Matches_Players");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.MatchLobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Lobbies_Status");

                    b.ToTable("MatchLobbies", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentElo")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentElo")
                        .HasDatabaseName("IX_Players_Elo");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Players_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Players_Username");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.PlayerScore", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageScore")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("PlayerId");

                    b.HasIndex("Rank")
                        .HasDatabaseName("IX_PlayerScores_Rank");

                    b.HasIndex("TotalScore")
                        .IsDescending()
                        .HasDatabaseName("IX_PlayerScores_TotalScore");

                    b.ToTable("PlayerScores", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.ResourceDeposit", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("GatherRate")
                        .HasColumnType("integer");

                    b.Property<int>("InitialCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_ResourceDeposits_Match");

                    b.ToTable("ResourceDeposits", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AttackDamage")
                        .HasColumnType("integer");

                    b.Property<int>("AttackRange")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealthPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MovementSpeed")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourcesCarried")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VisionRange")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId", "OwnerId")
                        .HasDatabaseName("IX_Units_Match_Owner");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Upgrade", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResearchProgress")
                        .HasColumnType("integer");

                    b.Property<int>("StartedAtTick")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchId", "Id");

                    b.HasIndex("MatchId", "PlayerId")
                        .HasDatabaseName("IX_Upgrades_Match_Player");

                    b.ToTable("Upgrades", (string)null);
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Building", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("Buildings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("BuildingMatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BuildingId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("PositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("PositionY");

                            b1.HasKey("BuildingMatchId", "BuildingId");

                            b1.ToTable("Buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingMatchId", "BuildingId");
                        });

                    b.OwnsMany("NetRts.Domain.Entities.ProductionOrder", "ProductionQueue", b1 =>
                        {
                            b1.Property<Guid>("BuildingMatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BuildingId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("TicksRemaining")
                                .HasColumnType("integer");

                            b1.Property<int>("TotalTicks")
                                .HasColumnType("integer");

                            b1.Property<string>("UnitType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BuildingMatchId", "BuildingId", "Id");

                            b1.ToTable("ProductionOrder");

                            b1.WithOwner()
                                .HasForeignKey("BuildingMatchId", "BuildingId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("ProductionQueue");
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Command", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("Commands")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "TargetPosition", b1 =>
                        {
                            b1.Property<long>("CommandId")
                                .HasColumnType("bigint");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("TargetPositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("TargetPositionY");

                            b1.HasKey("CommandId");

                            b1.ToTable("Commands");

                            b1.WithOwner()
                                .HasForeignKey("CommandId");
                        });

                    b.Navigation("TargetPosition");
                });

            modelBuilder.Entity("NetRts.Domain.Entities.LobbyPlayer", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.MatchLobby", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchLobbyId");
                });

            modelBuilder.Entity("NetRts.Domain.Entities.MapTile", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("MapTiles")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<int>("MapTileId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("PositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("PositionY");

                            b1.HasKey("MapTileId");

                            b1.ToTable("MapTiles");

                            b1.WithOwner()
                                .HasForeignKey("MapTileId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Match", b =>
                {
                    b.OwnsOne("NetRts.Domain.ValueObjects.Score", "Player1Score", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BuildingsDestroyed")
                                .HasColumnType("integer")
                                .HasColumnName("Player1_BuildingsDestroyed");

                            b1.Property<int>("BuildingsRemaining")
                                .HasColumnType("integer")
                                .HasColumnName("Player1_BuildingsRemaining");

                            b1.Property<int>("ResourcesGathered")
                                .HasColumnType("integer")
                                .HasColumnName("Player1_ResourcesGathered");

                            b1.Property<int>("UnitsDestroyed")
                                .HasColumnType("integer")
                                .HasColumnName("Player1_UnitsDestroyed");

                            b1.Property<int>("UnitsRemaining")
                                .HasColumnType("integer")
                                .HasColumnName("Player1_UnitsRemaining");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsOne("NetRts.Domain.ValueObjects.Score", "Player2Score", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BuildingsDestroyed")
                                .HasColumnType("integer")
                                .HasColumnName("Player2_BuildingsDestroyed");

                            b1.Property<int>("BuildingsRemaining")
                                .HasColumnType("integer")
                                .HasColumnName("Player2_BuildingsRemaining");

                            b1.Property<int>("ResourcesGathered")
                                .HasColumnType("integer")
                                .HasColumnName("Player2_ResourcesGathered");

                            b1.Property<int>("UnitsDestroyed")
                                .HasColumnType("integer")
                                .HasColumnName("Player2_UnitsDestroyed");

                            b1.Property<int>("UnitsRemaining")
                                .HasColumnType("integer")
                                .HasColumnName("Player2_UnitsRemaining");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Player1Score")
                        .IsRequired();

                    b.Navigation("Player2Score")
                        .IsRequired();
                });

            modelBuilder.Entity("NetRts.Domain.Entities.MatchLobby", b =>
                {
                    b.OwnsOne("NetRts.Domain.ValueObjects.GameSettings", "GameSettings", b1 =>
                        {
                            b1.Property<Guid>("MatchLobbyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CommandQueueSize")
                                .HasColumnType("integer")
                                .HasColumnName("CommandQueueSize");

                            b1.Property<int>("CommandsPerTick")
                                .HasColumnType("integer")
                                .HasColumnName("CommandsPerTick");

                            b1.Property<int>("MapHeight")
                                .HasColumnType("integer")
                                .HasColumnName("MapHeight");

                            b1.Property<int>("MapWidth")
                                .HasColumnType("integer")
                                .HasColumnName("MapWidth");

                            b1.Property<int>("MaxTicks")
                                .HasColumnType("integer")
                                .HasColumnName("MaxTicks");

                            b1.Property<int>("StartingResources")
                                .HasColumnType("integer")
                                .HasColumnName("StartingResources");

                            b1.Property<int>("TickIntervalMs")
                                .HasColumnType("integer")
                                .HasColumnName("TickIntervalMs");

                            b1.HasKey("MatchLobbyId");

                            b1.ToTable("MatchLobbies");

                            b1.WithOwner()
                                .HasForeignKey("MatchLobbyId");
                        });

                    b.Navigation("GameSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("NetRts.Domain.Entities.ResourceDeposit", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("ResourceDeposits")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("ResourceDepositMatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ResourceDepositId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("PositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("PositionY");

                            b1.HasKey("ResourceDepositMatchId", "ResourceDepositId");

                            b1.ToTable("ResourceDeposits");

                            b1.WithOwner()
                                .HasForeignKey("ResourceDepositMatchId", "ResourceDepositId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Unit", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("Units")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("UnitMatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("UnitId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("PositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("PositionY");

                            b1.HasKey("UnitMatchId", "UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitMatchId", "UnitId");
                        });

                    b.OwnsOne("NetRts.Domain.ValueObjects.Position", "TargetPosition", b1 =>
                        {
                            b1.Property<Guid>("UnitMatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("UnitId")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("TargetPositionX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("TargetPositionY");

                            b1.HasKey("UnitMatchId", "UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitMatchId", "UnitId");
                        });

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("TargetPosition");
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Upgrade", b =>
                {
                    b.HasOne("NetRts.Domain.Entities.Match", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetRts.Domain.Entities.Match", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Commands");

                    b.Navigation("MapTiles");

                    b.Navigation("ResourceDeposits");

                    b.Navigation("Units");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("NetRts.Domain.Entities.MatchLobby", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
